/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-prerelease-2.29.2-445-g9791069d7 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-prerelease-2.29.2-445-g9791069d7"
#endif
#define SDL_REVISION_NUMBER 0
